version: '3'
services:
  scrapper:
    build: .
    container_name: scrapper_container

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es_elgranbazarcervecero
    restart: unless-stopped
    volumes:
        - "./es_data:/usr/share/elasticsearch/data:rw"
    ports:
        - '9200:9200'
        - '9300:9300'
    environment:
        - discovery.type=single-node

  kib01:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana_elgranbazarcervecero
    restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://localhost:9200

  nginx-reverse-proxy:
    container_name: nginx_reverse_proxy
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - 8500:8500
      - 8501:80
    volumes:
      - ./nginx/conf.d/elgranbazarcervecero.conf:/etc/nginx/conf.d/default.conf
      - ./ui/:/usr/share/nginx/html
      