version: '3'
services:
  scrapper:
    build: .
    container_name: scrapper_container

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es_elgranbazarcervecero
    restart: unless-stopped
    volumes:
        - "./es_data:/usr/share/elasticsearch/data:rw"
    environment:
        - discovery.type=single-node

  # apache:
  #   image: 'bitnami/apache:latest'
  #   restart: unless-stopped
  #   ports:
  #     - '7080:8080'
  #     - '7443:8443'
  #   volumes:
  #     - ./ui:/app

  nginx-reverse-proxy:
    container_name: nginx_reverse_proxy
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - 8500:8500
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/

networks:
  default:
    external:
      name: elgranbazarcervecero-prod-net
      