version: '3'
services:
  scrapper:
    build: .
    container_name: scrapper_container

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: es_elgranbazarcervecero
    restart: unless-stopped
    volumes:
        - "./es_data:/usr/share/elasticsearch/data:rw"
    environment:
        - discovery.type=single-node

  nginx-reverse-proxy:
    container_name: nginx_reverse_proxy
    image: nginx:1.19
    restart: unless-stopped
    ports:
      - 8500:8500
      - 8501:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/conf.d/elgranbazarcervecero.prod.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    external:
      name: elgranbazarcervecero-prod-net
      